name: Azure Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: 0ad46259-baae-44b7-85c8-e51ac8ddc49e
          tenant-id: fa0f865c-7089-4b77-8d85-40eba1b81f1f
          subscription-id: 7b14aa4f-2974-4cef-ade6-15c62d590d01

      - name: Azure CLI Command
        run: |
          az account show
          az group list --output table
