name: Azure Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: d8e198cc-6b95-43aa-9ed6-86ddf9a5ff9c
          tenant-id: 612e50e3-aac1-45e7-97a6-221773393f77
          subscription-id: efaf257c-1149-4a6f-b413-fd403a3c5e58

      - name: Azure CLI Command
        run: |
          az account show
          az group list --output table
